[package]
name = "flashloan-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "deploy"
path = "src/deploy.rs"

[[bin]]
name = "execute"
path = "src/execute.rs"

[dependencies]
ethers = "2.0"
tokio = { version = "1", features = ["full"] }
hex = "0.4"
eyre = "0.6"
serde_json = "1.0"
